In [1]:
from Naive_Bayes import naive_bayes as nb
import numpy as np
import pandas as pd

In [2]:
data_ = pd.read_excel("data_latih/hasil_seleksi_New3.xlsx", sheet_name = "imbang")
komentar = data_['komentar'].tolist()
label = data_['label'].tolist()
data_.head()

Column1  Column12  Column2     label  \
0     1105         1      279      spam   
1    38121         2      216      spam   
2     2192         3      276  non spam   
3    48598         4      120      spam   
4    31006         5      848      spam   

                                            komentar  \
0  cuma orang aja berani lihat aksi video testimo...   
1  mau hp kalian liat lucu sini mampir casekarakt...   
2              kalau gin mirif kalem banget sih gaya   
3  murah murmer murah bangetbanting harga cuma ma...   
4  aku jadi makin pede ka berkat produk putih con...   

                                      komentar_kotor  
0  💞💞💞CUMA ORANG TERTENTU AJA YG BERANI LIHAT AKS...  
1  Hiii mau hp kalian keliatan lucu. Sini mampir ...  
2  Klo lgi kyk gini gak mirif mba via, kalem bgt ...  
3  WooOow MURAH MURMER MURAH bangetBANTING HARGA ...  
4  Akuuu jadii makiin pedde ajjja niiih ka  berkk...

In [3]:
# data_

In [4]:
# model = nb.NaiveBayesClassifier()

In [5]:
# model.train(komentar,np.array(label))

In [6]:
# model.predict([komentar[66247]])

In [7]:
# import joblib
# joblib.dump(model,"nbc.n")

In [8]:
# np.sum(x, axis=0)

In [9]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# corpus = [
#     'This is the first document.',
#     'This document is the second document.',
#     'And this is the third one.',
#     'Is this the first document?',
# ]
# vectorizer = TfidfVectorizer()
# X = vectorizer.fit_transform(corpus)
# print(vectorizer.get_feature_names())

# print(X.shape[1])


In [10]:
# len(np.sum(X[[1,2]],axis=0).A[1])

In [6]:
# model.dict_nb['spam']['n_yi'].A[0]+1

In [11]:
K = 10
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=K, random_state=2, shuffle=True)
skf
X = np.array(komentar)
y = np.array(label)
data_index = list()
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index] 
    y_train, y_test = y[train_index], y[test_index]
    x = {
        "X_train":X_train.tolist(),
        "y_train":y_train.tolist(),
        "X_test":X_test.tolist(),
        "y_test":y_test.tolist()
    }
    data_index.append(x)

In [12]:
# import joblib
# joblib.dump(data_index, "data_k_folds_10.data")
from json import dump

with(open("imbang_data_k_fold_10.json", "w")) as f:
    dump(data_index, f)

In [28]:
import numpy as np
from sklearn.feature_extraction.text import 
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

print(X.shape[1])


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
9


In [21]:
# np.std(X[[0,1]])
X.std(0)

AttributeError: std not found

In [22]:
x = np.matrix(np.arange(12).reshape((3, 4)))
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [23]:
x.std()

3.452052529534663

In [24]:
x.std(0)


matrix([[3.26598632, 3.26598632, 3.26598632, 3.26598632]])

In [25]:
x.std(1)

matrix([[1.11803399],
        [1.11803399],
        [1.11803399]])

In [38]:
from scipy import sparse
xxxx= sparse.csr_matrix(X.todense().mean(0))

In [44]:
X.A[0]

array([0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
       0.        , 0.38408524, 0.        , 0.38408524])

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

print(X.toarray())  

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [46]:
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [57]:
X.A^X.A[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [55]:
X.A^

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [53]:
X.A[0]

array([0, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)