In [13]:
import json
import pandas as pd
from Naive_Bayes import naive_bayes as nb
import numpy as np
import joblib

In [14]:
with open('imbang_data_k_fold_10.json') as json_file:
    data = json.load(json_file)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
# corpus = [
#     'This is the first document.',
#     'This document is the second document.',
#     'And this is the third one.',
#     'Is this the first document?',
# # ]
# vectorizer = TfidfVectorizer()
# X = vectorizer.fit_transform(corpus)
# print(vectorizer.get_feature_names())

# print(X.shape)

In [17]:
model_tf_idf = list()
model_tf = list()
model_bin = list()
# list_model = list()
for ix, i in enumerate(data):
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit(i['X_train'])
    data_latih = X.transform(i['X_train'])
    data_uji = X.transform(i['X_test'])
    dc={
        "model":X,
        "train":data_latih,
        "test":data_uji,
        "y_train":i['y_train'],
        "y_test":i['y_test'],
    }
    model_tf_idf.append(dc)
    
    vectorizer = CountVectorizer()
    X = vectorizer.fit(i['X_train'])
    data_latih = X.transform(i['X_train'])
    data_uji = X.transform(i['X_test'])
    dc={
        "model":X,
        "train":data_latih,
        "test":data_uji,
        "y_train":i['y_train'],
        "y_test":i['y_test'],
    }
    model_tf.append(dc)
    
    
    vectorizer = CountVectorizer(binary=True)
    X = vectorizer.fit(i['X_train'])
    data_latih = X.transform(i['X_train'])
    data_uji = X.transform(i['X_test'])
    dc={
        "model":X,
        "train":data_latih,
        "test":data_uji,
        "y_train":i['y_train'],
        "y_test":i['y_test'],
    }
    model_bin.append(dc)
    
    
    print(ix,end=".")


0.1.2.3.4.5.6.7.8.9.

In [19]:
import joblib
dict_model_ = {
    "model_tf_idf":model_tf_idf,
    "model_tf":model_tf,
    "model_bin":model_bin 
}
joblib.dump(dict_model_,"kfolds proses/imbang_data.dt")

['kfolds proses/imbang_data.dt']

In [4]:

model_ = dict()
list_model = list()
for ix, i in enumerate(data):
    model = nb.NaiveBayesClassifier()
    X = i['X_train']
    y = np.array(i['y_train'])
    model.train(X,y)
#     joblib.dump(m,"model_naive_bayes_kf/"+str(ix)+"_model.nbc")
#     joblib.dump(model,"model_naive_bayes_kf/"+str(ix)+"_model.nbc")
    list_model.append(model)
    print(ix,end=".")

0.1.2.3.4.5.6.7.8.9.

In [5]:
list_model[1].predict_(["kak suka langsing"])

['non spam']

In [10]:
alpha_list = np.arange(3.5, 7+0.5, 0.5)

In [11]:
from sklearn.metrics import accuracy_score

In [13]:
akurasi = list()
ixx= 0 
for alpha in alpha_list:
    acc_iterasi = list()
    for model in list_model:
        model.alpha = alpha
        for ix, i in enumerate(data):
            print(ixx, end='.')
            ixx+=1
            X = i['X_test']
            y = np.array(i['y_test'])
            y_ = model.predict_(X)
            y_pred = y_
            y_true = y
            acc_iterasi.append(accuracy_score(y_true, y_pred))
    akurasi.append(sum(acc_iterasi)/len(acc_iterasi))
    print(alpha, "|", sum(acc_iterasi)/len(acc_iterasi))

0.1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23.24.25.26.27.28.29.30.31.32.33.34.35.36.37.38.39.40.41.42.43.44.45.46.47.48.49.50.51.52.53.54.55.56.57.58.59.60.61.62.63.64.65.66.67.68.69.70.71.72.73.74.75.76.77.78.79.80.81.82.83.84.85.86.87.88.89.90.91.92.93.94.95.96.97.98.99.0.5 | 0.9700840807469996


In [ ]:
akurasi = list()
ixx= 0 
for alpha in alpha_list:
    acc_iterasi = list()
    for model in list_model:
        model.alpha = alpha
        for ix, i in enumerate(data):
            print(ixx, end='.')
            ixx+=1
            X = i['X_test']
            y = np.array(i['y_test'])
            y_ = model.predict(X)
            y_pred = y_
            y_true = y
            acc_iterasi.append(accuracy_score(y_true, y_pred))
    akurasi.append(sum(acc_iterasi)/len(acc_iterasi))
    print(alpha, "|", sum(acc_iterasi)/len(acc_iterasi))

0.1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23.24.25.26.27.28.29.30.31.32.33.34.35.36.37.38.39.40.41.42.43.44.45.46.47.48.49.50.51.52.53.54.55.56.57.58.59.60.61.62.63.64.65.66.67.68.69.70.71.72.73.74.75.76.77.78.79.80.81.82.83.84.85.86.87.88.89.90.91.92.93.94.95.96.97.98.99.0.5 | 0.9700840807469998
100.101.102.103.104.105.106.107.108.109.110.111.112.113.114.115.116.117.118.119.120.121.122.123.124.125.126.127.128.129.130.131.132.133.134.135.136.137.138.139.140.141.142.143.144.145.146.147.148.149.150.151.152.153.154.155.156.157.158.159.160.161.162.163.164.165.166.167.168.169.170.171.172.173.174.175.176.177.178.179.180.181.182.183.184.185.186.187.188.189.190.191.192.193.194.195.196.197.198.199.1.0 | 0.9687290008049868
200.201.202.203.204.205.206.207.208.209.210.211.212.213.

In [17]:
import numpy as np

m =[
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
    [9,2,3,4,5,6]
]

m = np.array(m)
m.transpose()

array([[1, 1, 1, 9],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [52]:
import numpy as np
from scipy import sparse
from scipy.sparse import csr_matrix, find

m =[
    [1,2,3,3,1,6],
    [2,4,1,2,2,1],
    [2,2,1,2,1,0],
    [9,1,2,4,0,3]
]

# m = np.matrix(m)
m = sparse.csr_matrix(m)
m.max(0).A
m

<4x6 sparse matrix of type '<class 'numpy.int32'>'
	with 22 stored elements in Compressed Sparse Row format>

In [50]:
m.A*m.max(0).A

array([[ 9,  8,  9, 12,  2, 36],
       [18, 16,  3,  8,  4,  6],
       [18,  8,  3,  8,  2,  0],
       [81,  4,  6, 16,  0, 18]], dtype=int32)

In [39]:
find(m.max(0))

(array([0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 1, 2, 3, 4, 5], dtype=int32),
 array([9, 4, 3, 4, 2, 6], dtype=int32))

In [29]:
B = m.tocsc()
col_argmax = [B.indices[B.indptr[i] + B.data[B.indptr[i]:B.indptr[i+1]].argmax()] for i in range(len(B.indptr)-1)]
col_argmax

[3, 1, 0, 3, 1, 0]

In [33]:
label = np.array(["a","b","c","d"])

In [36]:
label[col_argmax]

array(['d', 'b', 'a', 'd', 'b', 'a'], dtype='<U1')